version: '3'

services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
#    environment:
#      GITLAB_OMNIBUS_CONFIG: |
#        external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
      - '8929:8929'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab:Z'
      - '/srv/gitlab/logs:/var/log/gitlab:Z'
      - '/srv/gitlab/data:/var/opt/gitlab:Z'

  runner:
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    links:
            - "web:gitlab"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:Z'
      - '/srv/gitlab-runner/config:/etc/gitlab-runner:Z'

